const code = [
    {value: "中国", code: "86"},
    {value: "中国台湾", code: "886"},
    {value: "中国香港", code: "852"},
    {value: "中国澳门", code: "853"},
    {value: "Andorra", code: "376"},
    {value: "Afghanistan", code: "93"},
    {value: "Antigua and Barbuda", code: "1"},
    {value: "Anguilla", code: "1"},
    {value: "Albania", code: "355"},
    {value: "Armenia", code: "374"},
    {value: "Angola", code: "244"},
    {value: "Argentina", code: "54"},
    {value: "American Samoa", code: "1"},
    {value: "Austria", code: "43"},
    {value: "Australia", code: "61"},
    {value: "Aruba", code: "297"},
    {value: "Azerbaijan", code: "994"},
    {value: "Algeria", code: "213"},
    {value: "Bosnia and Herzegovina", code: "387"},
    {value: "Barbados", code: "1"},
    {value: "Bangladesh", code: "880"},
    {value: "Belgium", code: "32"},
    {value: "Burkina Faso", code: "226"},
    {value: "Bulgaria", code: "359"},
    {value: "Bahrain", code: "973"},
    {value: "Burundi", code: "257"},
    {value: "Benin", code: "229"},
    {value: "Bermuda", code: "1"},
    {value: "Brunei", code: "673"},
    {value: "Bolivia", code: "591"},
    {value: "Bonaire, Sint Eustatius and Saba", code: "599"},
    {value: "Brazil", code: "55"},
    {value: "Bahamas", code: "1"},
    {value: "Bhutan", code: "975"},
    {value: "Botswana", code: "267"},
    {value: "Belarus", code: "375"},
    {value: "Belize", code: "501"},
    {value: "British Indian Ocean Territory", code: "246"},
    {value: "British Virgin Islands", code: "1"},
    {value: "Canada", code: "1"},
    {value: "Cocos Islands", code: "61"},
    {value: "Central African Republic", code: "236"},
    {value: "Congo", code: "242"},
    {value: "Côte d'Ivoire", code: "225"},
    {value: "Cook Islands", code: "682"},
    {value: "Chile", code: "56"},
    {value: "Cameroon", code: "237"},
    {value: "China", code: "86"},
    {value: "Colombia", code: "57"},
    {value: "Costa Rica", code: "506"},
    {value: "Cuba", code: "53"},
    {value: "Cape Verde", code: "238"},
    {value: "Curaçao", code: "599"},
    {value: "Christmas Island", code: "61"},
    {value: "Cyprus", code: "357"},
    {value: "Czech Republic", code: "420"},
    {value: "Croatia", code: "385"},
    {value: "Cambodia", code: "855"},
    {value: "Comoros", code: "269"},
    {value: "Cayman Islands", code: "1"},
    {value: "Chad", code: "235"},
    {value: "Djibouti", code: "253"},
    {value: "Denmark", code: "45"},
    {value: "Dominica", code: "1"},
    {value: "Dominican Republic", code: "1"},
    {value: "Ecuador", code: "593"},
    {value: "Estonia", code: "372"},
    {value: "Egypt", code: "20"},
    {value: "Eritrea", code: "291"},
    {value: "Ethiopia", code: "251"},
    {value: "Equatorial Guinea", code: "240"},
    {value: "El Salvador", code: "503"},
    {value: "Finland", code: "358"},
    {value: "Fiji", code: "679"},
    {value: "Falkland Islands", code: "500"},
    {value: "Faroe Islands", code: "298"},
    {value: "France", code: "33"},
    {value: "French Guiana", code: "594"},
    {value: "French Polynesia", code: "689"},
    {value: "Germany", code: "49"},
    {value: "Gabon", code: "241"},
    {value: "Grenada", code: "1"},
    {value: "Georgia", code: "995"},
    {value: "Guernsey", code: "44"},
    {value: "Ghana", code: "233"},
    {value: "Gibraltar", code: "350"},
    {value: "Greenland", code: "299"},
    {value: "Gambia", code: "220"},
    {value: "Guinea", code: "224"},
    {value: "Guadeloupe", code: "590"},
    {value: "Greece", code: "30"},
    {value: "Guatemala", code: "502"},
    {value: "Guam", code: "1"},
    {value: "Guinea-Bissau", code: "245"},
    {value: "Guyana", code: "592"},
    {value: "Hong Kong", code: "852"},
    {value: "Honduras", code: "504"},
    {value: "Haiti", code: "509"},
    {value: "Hungary", code: "36"},
    {value: "Ireland", code: "353"},
    {value: "Israel", code: "972"},
    {value: "Isle Of Man", code: "44"},
    {value: "India", code: "91"},
    {value: "Indonesia", code: "62"},
    {value: "Iraq", code: "964"},
    {value: "Iran", code: "98"},
    {value: "Iceland", code: "354"},
    {value: "Italy", code: "39"},
    {value: "Jersey", code: "44"},
    {value: "Jamaica", code: "1"},
    {value: "Jordan", code: "962"},
    {value: "Japan", code: "81"},
    {value: "Kenya", code: "254"},
    {value: "Kyrgyzstan", code: "996"},
    {value: "Kiribati", code: "686"},
    {value: "Kuwait", code: "965"},
    {value: "Kazakhstan", code: "7"},
    {value: "Laos", code: "856"},
    {value: "Lebanon", code: "961"},
    {value: "Liechtenstein", code: "423"},
    {value: "Liberia", code: "231"},
    {value: "Lesotho", code: "266"},
    {value: "Lithuania", code: "370"},
    {value: "Luxembourg", code: "352"},
    {value: "Latvia", code: "371"},
    {value: "Libya", code: "218"},
    {value: "Micronesia", code: "691"},
    {value: "Morocco", code: "212"},
    {value: "Monaco", code: "377"},
    {value: "Moldova", code: "373"},
    {value: "Montenegro", code: "382"},
    {value: "Madagascar", code: "261"},
    {value: "Marshall Islands", code: "692"},
    {value: "Macedonia", code: "389"},
    {value: "Mali", code: "223"},
    {value: "Myanmar", code: "95"},
    {value: "Mongolia", code: "976"},
    {value: "Macao", code: "853"},
    {value: "Martinique", code: "596"},
    {value: "Mauritania", code: "222"},
    {value: "Montserrat", code: "1"},
    {value: "Malta", code: "356"},
    {value: "Mauritius", code: "230"},
    {value: "Maldives", code: "960"},
    {value: "Malawi", code: "265"},
    {value: "Mexico", code: "52"},
    {value: "Malaysia", code: "60"},
    {value: "Mozambique", code: "258"},
    {value: "Mayotte", code: "262"},


    {value: "North Korea", code: "850"},
    {value: "Northern Mariana Islands", code: "1"},
    {value: "Namibia", code: "264"},
    {value: "New Caledonia", code: "687"},
    {value: "Niger", code: "227"},
    {value: "Norfolk Island", code: "672"},
    {value: "Nigeria", code: "234"},
    {value: "Nicaragua", code: "505"},
    {value: "Netherlands", code: "31"},
    {value: "Norway", code: "47"},
    {value: "Nepal", code: "977"},
    {value: "Nauru", code: "674"},
    {value: "Niue", code: "683"},
    {value: "New Zealand", code: "64"},

    {value: "Panama", code: "507"},
    {value: "Peru", code: "51"},
    {value: "Papua New Guinea", code: "675"},
    {value: "Philippines", code: "63"},
    {value: "Pakistan", code: "92"},
    {value: "Poland", code: "48"},
    {value: "Puerto Rico", code: "1"},
    {value: "Palestine", code: "970"},
    {value: "Portugal", code: "351"},
    {value: "Palau", code: "680"},
    {value: "Paraguay", code: "595"},

    {value: "Qatar", code: "974"},

    {value: "Reunion", code: "262"},
    {value: "Romania", code: "40"},
    {value: "Russia", code: "7"},
    {value: "Rwanda", code: "250"},

    {value: "Saint Barthélemy", code: "590"},
    {value: "Switzerland", code: "41"},
    {value: "Spain", code: "34"},
    {value: "Saint Kitts And Nevis", code: "1"},
    {value: "South Korea", code: "82"},
    {value: "Saint Lucia", code: "1"},
    {value: "Sri Lanka", code: "94"},
    {value: "Saint Martin", code: "590"},
    {value: "Saint Pierre And Miquelon", code: "508"},
    {value: "Serbia", code: "381"},
    {value: "Saudi Arabia", code: "966"},
    {value: "Solomon Islands", code: "677"},
    {value: "Seychelles", code: "248"},
    {value: "Sudan", code: "249"},
    {value: "Sweden", code: "46"},
    {value: "Singapore", code: "65"},
    {value: "Saint Helena", code: "290"},
    {value: "Slovenia", code: "386"},
    {value: "Svalbard And Jan Mayen", code: "47"},
    {value: "Slovakia", code: "421"},
    {value: "Sierra Leone", code: "232"},
    {value: "San Marino", code: "378"},
    {value: "Senegal", code: "221"},
    {value: "Somalia", code: "252"},
    {value: "Surivalue", code: "597"},
    {value: "Sao Tome And Principe", code: "239"},
    {value: "Sint Maarten (Dutch part)", code: "1"},
    {value: "Syria", code: "963"},
    {value: "Swaziland", code: "268"},
    {value: "Saint Vincent And The Grenadines", code: "1"},
    {value: "Samoa", code: "685"},
    {value: "South Africa", code: "27"},
    {value: "The Democratic Republic Of Congo", code: "243"},
    {value: "Turks And Caicos Islands", code: "1"},
    {value: "Togo", code: "228"},
    {value: "Thailand", code: "66"},
    {value: "Tajikistan", code: "992"},
    {value: "Tokelau", code: "690"},
    {value: "Timor-Leste", code: "670"},
    {value: "Turkmenistan", code: "993"},
    {value: "Tunisia", code: "216"},
    {value: "Tonga", code: "676"},
    {value: "Turkey", code: "90"},
    {value: "Trinidad and Tobago", code: "1"},
    {value: "Tuvalu", code: "688"},
    {value: "Taiwan", code: "886"},
    {value: "Tanzania", code: "255"},
    {value: "United Arab Emirates", code: "971"},
    {value: "United Kingdom", code: "44"},
    {value: "Ukraine", code: "380"},
    {value: "Uganda", code: "256"},
    {value: "United States", code: "1"},
    {value: "Uruguay", code: "598"},
    {value: "Uzbekistan", code: "998"},
    {value: "U.S. Virgin Islands", code: "1"},
    {value: "Vatican", code: "379"},
    {value: "Venezuela", code: "58"},
    {value: "Vietnam", code: "84"},
    {value: "Vanuatu", code: "678"},
    {value: "Western Sahara", code: "212"},
    {value: "Wallis And Futuna", code: "681"},
    {value: "Yemen", code: "967"},
    {value: "Zambia", code: "260"},
    {value: "Zimbabwe", code: "263"}

];
export default  code;