#feign
feign:
    sentinel:
        enabled: true
#开启监控
management:
    endpoints:
        web:
            exposure:
                include: '*'
#mybatis
mybatis:
    configuration:
        cache-enabled: true
    mapper-locations: classpath*:/mapper/*Mapper.xml
    type-aliases-package: com.ratta.domain
redis:
    cache:
        expires: 1

#服务注册中心nacos-discovery
spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    cloud:
        nacos:
            discovery:
                namespace: e86d662e-11b6-4bcf-b1c7-dc3913e913c5
                server-addr: 10.20.22.30:8848
#Sentinel
        sentinel:
            transport:
                dashboard: 10.20.22.30:8888
#springCloudStream
#============== kafka ===================
        stream:
            bindings:
                user_output:
                    destination: user_service
                    contentType: application/json
                equipment_output:
                    destination: equipment_service
                    contentType: application/json
                cms_output:
                    destination: cms_service
                    contentType: application/json
            default-binder: kafka
            #spring.cloud.stream.kafka.binder.replicationFactor=2
            kafka:
                binder:
                    min-partition-count: 5
    #druid.datasource
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        druid:
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            filters: stat,wall,slf4j
            initialSize: 5
            maxActive: 20
            maxPoolPreparedStatementPerConnectionSize: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 5
            poolPreparedStatements: true
            stat-view-servlet:
                enabled: true
                login-password: druid
                login-username: druid
                reset-enable: true
                url-pattern: /druid/*
            testOnBorrow: false
            testOnReturn: false
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            useGlobalDataSourceStat: true
            validationQuery: SELECT 1 FROM DUAL
        password: enote123
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mariadb://10.20.22.31:3306/systembasedb?useUnicode=true&characterEncoding=utf-8
        username: enote
#以逗号分隔的主机：端口对列表，用于建立与Kafka群集的初始连接
    kafka:
        bootstrap-servers: 10.20.22.30:9093
        #=============== consumer  =======================
        consumer:
            auto-commit-interval: 100
            auto-offset-reset: earliest
            # true=自动提交；false=手动提交
            enable-auto-commit: false
            group-id: system-base-group
            #=============== provider  =======================
#如果该值大于零时，表示启用重试失败的发送次数
        producer:
        # all,-1,0,1 
            acks: -1
            #批量发送消息字节数，默认值为16384
            batch-size: 16384
            #生产者可用于缓冲等待发送到服务器的记录的内存总字节数，默认值为33554432
            buffer-memory: 33554432
            retries: 0
    # REDIS (RedisProperties)
    redis:
        database: 0
        host: 10.20.22.30
        port: 6379
        password: 
        timeout: 5000
        cache: 
            expires: 720
    sleuth:
        sampler:
        #区间是0.1到1， 1代表保存所有的链路， 0.1表示保存10%的链路
            probability: 1
            #springCloudSleuth
    zipkin:
        baseUrl: http://10.20.22.30:9411/
        enabled: true
        sender:
            type: kafka
        service:
            name: system-base-service
domain: .ratta.com.cn
